### ISSUE TITLE
Issues with 1.0.8 output

### ISSUE THREAD

**Issue by gevro** [genepi/haplocheck#10]
Hi,
A few issues with the output of the new version.

1) The word "amount" is still used and is unclear what this means.
2) Major Heteroplasmy Level and Minor Heteroplasmy Level are now empty. This is probably a bug.

See example below:
"Sample"	"Contamination Status"	"Overall Homoplasmies"	"Overall Heteroplasmies"	"Sample Coverage"	"Major Haplogroup"	"Major Haplogroup Quality"	"Minor Haplogroup"	"Minor Haplogroup Quality"	"Amount Major Homoplasmies"	"Amount Minor Homoplasmies"	"Amount Major Heteroplasmies"	"Amount Minor Heteroplasmies"	"Major Heteroplasmy Level"	"Minor Heteroplasmy Level"	"Distance"	"Clusters"
"sample.bam"	"NO"	"33"	"25"	"3382"	"U8b1b2"	"0.926"	"U8b1b2"	"0.911"	"26"	"26"	"0"	"0"	" "	" "	"0"	""

**Comment by seppinho** [comment]
Thanks. I updated the code to match the documentation: "Major Homoplasmies Count" and so on.
