### ISSUE TITLE
Bug in new version output

### ISSUE THREAD

**Issue by gevro** [genepi/haplocheck#11]
Hi,
There is a bug in the new version's output:

"Sample"	"Contamination Status"	"Overall Homoplasmies"	"Overall Heteroplasmies"	"Sample Coverage"	"Major Haplogroup"	"Major Haplogroup Quality"	"Minor Haplogroup"	"Minor Haplogroup Quality"	"Amount Major Homoplasmies"	"Amount Minor Homoplasmies"	"Amount Major Heteroplasmies"	"Amount Minor Heteroplasmies"	"Major Heteroplasmy Level"	"Minor Heteroplasmy Level"	"Distance"	"Clusters"
"UDP-1103_genome.realigned.bam"	"YES"	"32"	"40"	"3450"	"R30b1"	"0.828"	"R+16189"	"0.650"	"22"	"12"	"7"	"0"	"0.988"	" "	"4"	"0.984 (1);0.988 - 0.99 (6);"

Minor Heteroplasmy level is empty.

**Comment by gevro** [comment]
Hi, In another sample, both major and minor heteroplasmy levels are empty:
"Sample"	"Contamination Status"	"Overall Homoplasmies"	"Overall Heteroplasmies"	"Sample Coverage"	"Major Haplogroup"	"Major Haplogroup Quality"	"Minor Haplogroup"	"Minor Haplogroup Quality"	"Amount Major Homoplasmies"	"Amount Minor Homoplasmies"	"Amount Major Heteroplasmies"	"Amount Minor Heteroplasmies"	"Major Heteroplasmy Level"	"Minor Heteroplasmy Level"	"Distance"	"Clusters"
"UDP-1003_genome.realigned.bam"	"NO"	"33"	"25"	"3382"	"U8b1b2"	"0.926"	"U8b1b2"	"0.911"	"26"	"26"	"0"	"0"	" "	" "	"0"	""

**Comment by seppinho** [comment]
I made it clearer by adding n/a when the level can not be calculated.
https://github.com/genepi/haplocheck/commit/58635d9151ad601708cdd912c28231fff63f0739
