### ISSUE TITLE
What does ND mean?

### ISSUE THREAD

**Issue by ManavalanG** [genepi/haplocheck#16]
Allowed values for "Contamination Status" are YES, NO and ND. What does ND mean? Besides that it [stands for "not detectable"](https://mitoverse.readthedocs.io/haplocheck/haplocheck/#contamination-status), I couldn't find in doc what exactly it means (in terms of criteria used).

**Comment by haansi** [comment]
Hi! ND does mean there are no heteroplasmic variants found (criteria: heteroplasmic varinats ==0)  so we can't make any analysis - this can have two main reasons: coverage too low to detect any heteroplasmic variant at all, or if coverage is deep, that there is indeed no contamination.

**Comment by ManavalanG** [comment]
Thanks for the explanation!
