### ISSUE TITLE
Haplocheck output into multiQC

### ISSUE THREAD

**Issue by peterpru** [genepi/haplocheck#20]
It would be beneficial to have the haplocheck output compatible with the multiQC.html and multiqc_data.json file generated by multiQC for downstream processing of the output.

**Comment by peterpru** [comment]
MultiQC issue opened here: https://github.com/MultiQC/MultiQC/issues/2932

**Comment by peterpru** [comment]
MultiQC PR opened here: https://github.com/MultiQC/MultiQC/pull/2933

**Comment by peterpru** [comment]
Closed as completed.

**Comment by seppinho** [comment]
Thank you for integrating Haplocheck into multiQC!
