### ISSUE TITLE
Divide by zero error on mean coverage sample calculation due to assuming there is at least one variant

### ISSUE THREAD

**Issue by monkollek** [genepi/haplocheck#3]
The divide by zero can happen here:
https://github.com/genepi/haplocheck/blob/master/src/main/java/genepi/haplocheck/steps/contamination/ContaminationDetection.java#L82

When the haplogroup of the sample is the same as the reference haplogroup, you can get a scenario that there will be no variants causing a divide by zero problem. Using this method you can't get the mean sample coverage and may need to use DP from 0/0.

**Comment by seppinho** [comment]
see https://github.com/genepi/haplocheck/commit/65e9262fdb534a1cfc7fd66572e4e0b4e35a7aee
