### ISSUE TITLE
Retrieving variant counts (within ContaminationDetection) can be problematic 

### ISSUE THREAD

**Issue by monkollek** [genepi/haplocheck#4]
The assumption is that there is at least one variant (e.g. homoplasmic variant)
https://github.com/genepi/haplocheck/blob/master/src/main/java/genepi/haplocheck/steps/contamination/ContaminationDetection.java#L79-L82

Otherwise it will remain undefined
https://github.com/seppinho/haplogrep-core/blob/master/src/vcf/Sample.java#L10-L12

Though incrementing an undefined value (assuming it's zero) can be problematic
https://github.com/seppinho/haplogrep-core/blob/master/src/vcf/Sample.java#L54-L61

I went back and set the variables to zero on object creation
private int amountHomoplasmies = 0;
private int amountVariants = 0;
private int amountHeteroplasmies = 0;

**Comment by seppinho** [comment]
thanks. really appreciate your tests

**Comment by seppinho** [comment]
see https://github.com/seppinho/haplogrep-core/commit/a40a36166297f1f9577f289d5267938522863b86
