### ISSUE TITLE
Problems retrieving sample ids with spaces

### ISSUE THREAD

**Issue by monkollek** [genepi/haplocheck#5]
Yes, we shouldn't have spaces in sample ids but welcome to my life!

This sample id will no longer have a space
https://github.com/genepi/haplocheck/blob/master/src/main/java/genepi/haplocheck/steps/contamination/ContaminationDetection.java#L73

Due to this replace of a space with an underscore
https://github.com/seppinho/haplogrep-core/blob/master/src/core/TestSample.java#L73

So this retrieval will fail as the sample id will no longer have a space in it but an underscore
https://github.com/genepi/haplocheck/blob/master/src/main/java/genepi/haplocheck/steps/contamination/ContaminationDetection.java#L77

For now I have edited this line and remove the replace calls
https://github.com/seppinho/haplogrep-core/blob/master/src/core/TestSample.java#L73

that is
parsedSample.testSampleID = columns[0].trim()

**Comment by seppinho** [comment]
thanks. Has been fixed in haplogrep-core and test case added.  Fyi, since core is also used in the web service I added the same check when reading in files from VCF.
