### ISSUE TITLE
Contamination output file versus old version of haplochecker

### ISSUE THREAD

**Issue by gevro** [genepi/haplocheck#6]
Hi, I am trying to adapt a pipeline that used the old version of haplochecker. This was the contamination output:
SampleID Contamination MinorHG MinorLevel MinorSNPs MinorHGvariants MajorHG MajorLevel MajorSNPs MajorHGvariants VerifyScore meanCovVar HG_Distance
genome.realigned.bam None U8b1b2 0.988 24/30 3 U8b1b2 0.000 24/30 1 0.0 3260.0 0

Here is the contamination output from the new cloudgene version of haplocheck (this repository):
"SampleID"	"Contamination"	"SampleHomoplasmies"	"SampleHeteroplasmies"	"SampleMeanCoverage"	"HgMajor"	"HgQualityMajor"	"HgMinor""HgQualityMinor"	"HomoplasmiesMajor"	"HomoplasmiesMinor"	"HeteroplasmiesMajor"	"HeteroplasmiesMinor"	"MeanHetLevelMajor"	"MeanHetLevelMinor"	"HG_Distance"	"Clusters"
"blah.bam"	"YES"	"32"	"40"	"3450"	"R30b1"	"0.828"	"R+16189"	"0.650"	"22"	"12"	"7"	"0"	"0.989"	"0.000"	"4"	"0.984 (1);0.988 - 0.99 (6);"

Questions:
1) What is the equivalent to the VAF option in the old haplochecker when running the new haplocheck?
"    --VAF <double>    set the Variant Allele Frequency (VAF), example
                     [0.1] = 10%)"

2) The old version of haplochecker had an option to specify the REF. How come this is no longer needed?
"    --ref <string>   reference FASTA file"

3) What are the equivalents of MinorLevel and MajorLevel of the old haplochecker in the new haplocheck output? Those are the key parameters I need for my pipeline and I want to be sure I'm using the right thing.
Thanks.

**Comment by seppinho** [comment]
Hi, sorry for the confusion. 
- So in haplocheck we split variant calling from the process of contamination check. The variables --ref and --VAF are set in the variant calling step (can not be altered at the moment, so VAF is currently 1 %). See here: https://github.com/genepi/haplocheck/blob/master/files/cloudgene.yaml I can provide a version where these options can be set from command line. 
- MinorLevel and MajorLevel are now MeanHetLevelMinor amd MeanHetLevelMajor

**Comment by gevro** [comment]
Thanks. Are the contamination levels possible to calculate without inputting the REF (reference)?
In other words, the reference was never used for contamination calculations, and was only used for variant calling?

**Comment by seppinho** [comment]
I will also add this to the documentation
