### ISSUE TITLE
Major Level and Minor Level = 0%

### ISSUE THREAD

**Issue by gevro** [genepi/haplocheck#7]
Hi. I ran a standard haplocheck analysis and the report said Major Level and Minor Level is 0%, with No contamination.

Here is the contamination.txt file:
"SampleID"     	 "Contamination" 	 "SampleHomoplasmies" 	 "SampleHeteroplasmies" 	 "SampleMeanCoverage" 	 "HgMajor" 	 "HgQualityMajor" 	 "HgMinor" 	 "HgQualityMinor" 	 "HomoplasmiesMajor" 	 "HomoplasmiesMinor" 	 "HeteroplasmiesMajor" 	 "HeteroplasmiesMinor" 	 "MeanHetLevelMajor" 	 "MeanHetLevelMinor" 	 "HG_Distance" 	 "Clusters"
"UDP-1003.bam" 	 "NO"            	 "33"                 	 "25"                   	 "3269"               	 "U8b1b2"  	 "0.926"          	 "U8b1b2"  	 "0.911"          	 "26"                	 "26"                	 "0"                   	 "0"                   	 "0.000"             	 "0.000"             	 "0"           	 ""

This looks odd to me. First, I don't understand the meaning of each of the columns. But regardless, how can the Major HG level be 0%

Thanks.

**Comment by seppinho** [comment]
Hi, information can be found here: https://mitoverse.readthedocs.io/en/latest/analyse/
Regarding the Levels: Since no heteroplasmies could be found, the HG levels are 0. I will update the version that no value will be calculated in such a case.

**Comment by gevro** [comment]
Thanks. However, I'm still confused -- if there are no heteroplasmies, shouldn't the Major HG level = 100% ?

**Comment by seppinho** [comment]
Excellent question. So the score is calculated using Haplogrep, for details see here: http://haplogrep.uibk.ac.at/blog/explaining-the-formula/
So in case a (homoplasmic) variant is missing in the input file or not all variants are used from the best haplogroup hit, the level can be <100% (even if no heteroplasmic pos are included)

**Comment by gevro** [comment]
That makes sense. However, the question above was why the Major and Minor levels of my sample were both 0% (**zero**). How is that possible? I am assuming it is a bug in haplocheck.

**Comment by seppinho** [comment]
Ok so regarding this question: Major and minor level are calculated by taking into account all heteroplasmies from the common ancestor. In this case there are no heteroplasmies, so we can not calculate the levels. I just commited a fix, that levels are only calcualted iff heteroplasmies > 0

**Comment by gevro** [comment]
Great. Can you clarify then what the values will be for Major and minor levels if no heteroplasmies are found? Major level should = 1.0 in my opinion in those situations.

**Comment by seppinho** [comment]
So it's the major/minor heteroplasmy level. So if both haplogroups are identical and no heteroplasmies could be found, both levels must be 0. So these two levels only make sense if contamination status is "YES". Does this make sense?

**Comment by seppinho** [comment]
Regarding UDP-1003.bam: We split the file by homoplasmic and heteroplasmic positions. So homoplasmic positions are added to both profiles, heteroplasmic positions split by major/minor. So having the same haplogroup for both profiles is valid (since there is no contamination). Only haplogroup differences would indicate a contamination based on mtDNA

**Comment by gevro** [comment]
I'm still not sure I understand. In a situation where there is only one major haplogroup (Contamination = "NO"), the major haplogroup level should = 1.0, and minor haplogroup level should = 0 or Null. I'm not sure I understand why major haplogroup level = 0 when there is no contamination, because 100% of the mitochondria are from the major haplogroup in that situation.

**Comment by seppinho** [comment]
Hi again.
There are two values calculated: The HgQualityMajor (=major haplogroup level) and the MeanHetLevelMajor (= major heteroplasmy level) (same for minor).  The major/minor haplogroup level is calculated by Haplogrep, the interesting value is the major/minor heteroplasmy level. 
Let's have a look at your sample:
- No contamination detected. Both haplogroups showing a good quality (0.926, 0.911). The 26 homoplasmic positions are used to calculate this level. Since homoplasmic pos are added to both profiles, it makes sense that both levels (HgQualityMajor,HgQualityMinor) are high. The Heteroplasmy Levels (MeanHetLevelMajor/Minor) are both zero, since no heteroplasmies could be found.  

- So in a "NO" scenario: Identical haplogroups are found (or max distance of 2), both haplogroup quality levels are high and both heteroplasmy levels are low.
- In a "Yes" scenario:  haplogroups differ, still both haplogroup quality levels are high, one high heteroplasmy level / one low heteroplasmy level. 
- There are also bit more complicated cases with the levels (depending if the haplogroups are on different branches).

Really appreciate your feedback and your input. If is still unclear, I will try to write a example with graphical output. This would probably clarify my thoughts.

**Comment by gevro** [comment]
Hi again, Thank you so much for these explanations! But I'm afraid to say that I still don't  understand. I think the issue is that the terms/columns are not clearly defined, and I think once you define these terms for me, I will understand. Perhaps it might help others too if this is added to the documentation.

There are 6 important columns: HgMajor, HgMinor, HgQualityMajor, HgQualityMinor, MeanHetLevelMajor, MeanHetLevelMinor.

You said that HgQualityMajor/HgQualityMinor = major/minor haplogroup level. However, why do these columns contain the word 'Quality', if they are measuring the 'level'? At the same time, a different set of columns called MeanHetLevelMajor/MeanHetLevelMinor you wrote equal major/minor heteroplasmy level. So there is confusion about quality vs level, and what the difference is between these terms. You also mention the term "quality level" so this combines both terms in a way that is not clear.

1) Can you define each of these 6 columns and how they are calculated? And also specifically what the term "quality" means, what "level" means, and what "quality level" means?

2) Second, the outputs for the different scenarios are a bit confusing. For example, if no contamination is detected, doesn't that mean there is no minor haplogroup? If so, then minor haplogroup values should be set to 0 and the minor haplogroup name should be set to NULL instead of the same name as the major haplogroup.

3) In the "Yes" contamination scenario: what is the threshold minor HG level that you consider as being detectable? Is this the VAF parameter?

I saw that you have a diagram on your website here: https://mitoverse.readthedocs.io/en/latest/method/ . But this diagram does not mention the above 6 columns and how they each relate to the different situations. Perhaps it might help to update that page with these 6 columns.

Thanks again!!

**Comment by seppinho** [comment]
Great points. I'll update the documentation today and let you know. Thanks for taking the time to improve haplocheck. Really appreciate that!

**Comment by seppinho** [comment]
Hi again,
So I tried to include all simplify the documentation and explanation of the result file. Please have a look and let me know if it helps: https://mitoverse.readthedocs.io/en/latest/interpret/

**Comment by gevro** [comment]
Thanks! This is very helpful. Some feedback to make it more clear:
- The term 'amount' is ambiguous, and it would be good to define this.
- What is the difference b/w overall homo/heteroplasmies and amount major/minor homo/heteroplasmies?
- Heteroplasmy "level" - the word level is still not defined. What does this represent? Read depth? Fraction of reads for an allele out of the total read depth? Quality score?
- It is not clear how the label Contamination = YES versus = NO is decided exactly.
- The definitions of each annotation do not match the column headers in the final contamination.txt output. For example, you write "Major heteroplasmy level" in your new explanation, but there is no such column header in contamination.txt. I am guessing this refers to MeanHetLevelMajor? Would be important to clearly link each item to the contamination.txt file to help users understand the meaning of the program's output.
- The output still doesn't make sense in the prior situation I listed above:
""SampleID" "Contamination" "SampleHomoplasmies" "SampleHeteroplasmies" "SampleMeanCoverage" "HgMajor" "HgQualityMajor" "HgMinor" "HgQualityMinor" "HomoplasmiesMajor" "HomoplasmiesMinor" "HeteroplasmiesMajor" "HeteroplasmiesMinor" "MeanHetLevelMajor" "MeanHetLevelMinor" "HG_Distance" "Clusters"
"UDP-1003.bam" "NO" "33" "25" "3269" "U8b1b2" "0.926" "U8b1b2" "0.911" "26" "26" "0" "0" "0.000" "0.000" "0" """
   - Both the major and minor haplogroups are the same, which doesn't make sense, and the levels are 0 for both, which doesn't make sense. Per the suggestion above, when you are unable to calculate a level, then you should use "NULL" or other kinds of outputs, instead of 0. Zero indicates a measured level, but this needs to be distinguished from situations where the level cannot be calculated.

Hope this helps.

**Comment by seppinho** [comment]
Hi again,
Thanks again for the feedback. I hope I could clarify one or the other point. If not, please let me know.
- Point 0: Amount is now denoted by count.
- Points 2-4 have been added here: https://mitoverse.readthedocs.io/en/latest/faq/
- Point 5: I added the old column names in brackets. v1.0.7 uses new and hopefully clearer column headers. https://mitoverse.readthedocs.io/en/latest/interpret/
- Point 6: So even if 25 heteroplasmies have been found, no one is used for the major or minor profile. This can have several reasons. The abvious one is that no one of the heteroplasmy alleles is included in the phylogeny. Therefore the best hit for both is U8b1b2. Therefore no contamination identified.

**Comment by gevro** [comment]
Thank you. This is now much more clear.
