### ISSUE TITLE
MeanHetLevelMinor = 0 when contamination = YES

### ISSUE THREAD

**Issue by gevro** [genepi/haplocheck#8]
Hi, I have a sample for which the Contamination = YES, but the MeanHetLevelMinor = 0. This should not be possible, because by definition, if there is a minor haplogroup, then there should be some level of the minor heteroplasmies that are > 0. 

"SampleID"	"Contamination"	"SampleHomoplasmies"	"SampleHeteroplasmies"	"SampleMeanCoverage"	"HgMajor"	"HgQualityMajor"	"HgMinor"	"HgQualityMinor"	"HomoplasmiesMajor"	"HomoplasmiesMinor"	"HeteroplasmiesMajor"	"HeteroplasmiesMinor"	"MeanHetLevelMajor"	"MeanHetLevelMinor"	"HG_Distance"	"Clusters"
"SAMPLE"	"YES"	"32"	"40"	"3450"	"R30b1"	"0.828"	"R+16189"	"0.650"	"22"	"12"	"7"	"0"	"0.989"	"0.000"	"4"	"0.984 (1);0.988 - 0.99 (6);"

**Comment by seppinho** [comment]
Thanks. I will update the documentation to clarify also this scenario.

**Comment by seppinho** [comment]
Great example. So haplocheck identified contamination. For the major haplogroup (R30b1) 22 homoplasmies and 7 heteroplasmies have been used. Haplocheck is able to calculate a heteroplasmy level (average VAF of major heteroplasmy is 0.989). For the minor haplogroup, no heteroplasmies are used. So the contamination is on the same branch and no level can be calculated. If you have a look at the phylogenetic tree (report.html), you will see that both profiles are on the same branch. Please have a look at the contamination method in the docs. Scenario B or C is exactly what you are experiencing here: https://mitoverse.readthedocs.io/en/latest/method/

**Comment by gevro** [comment]
Hi, Thanks. However, how does the software call a minor haplogroup without any heteroplasmies? I'm confused what that means. If there are no heteroplasmies for a lineage on the same branch, how come it is not just one major haplogroup without a minor haplogroup?

**Comment by seppinho** [comment]
Excellent question. Answer: The minor haplogroup consists of homoplasmies only. So as discussed, heteroplasmies are split into two components. Profile1 adds the major part of the heteroplasmy to the input profile and uses them to assign the best haplogroup hit. Profile2 adds the minor part of the heteroplasmy to the input profile but they are not used when assiging the best haplogroup hit. But still: the minor haplogroup differs from the major haplogroup and this can be detected as contamination. The main question is why the minor heteroplasmy parts are not used: One abvious reason is that the phylogeny in some of the branches is not perfect (not like in H) and sub-lineages are still missing. Therefore the minor haplogroup is part of a super-haplogroup. Fyi, this can also happen to the major haplogroup. Scenario B and C are discussing this: https://mitoverse.readthedocs.io/en/latest/method/
